package com.tencent.mm.plugin.expt.a;

import com.tencent.matrix.trace.core.AppMethodBeat;

public enum a$b
{
  static
  {
    AppMethodBeat.i(128624);
    lJn = new b("mmclient_expt_test", 0);
    lJo = new b("clicfg_open_mix_audio", 1);
    lJp = new b("clicfg_open_pre_draw", 2);
    lJq = new b("clicfg_ad_landing_page_new_stream_video", 3);
    lJr = new b("clicfg_appbrand_game_predownload", 4);
    lJs = new b("clicfg_appbrand_game_split_codelib", 5);
    lJt = new b("clicfg_keepaliveserviceswitch", 6);
    lJu = new b("clicfg_matrix_trace_fps_enable", 7);
    lJv = new b("clicfg_matrix_trace_care_scene_set", 8);
    lJw = new b("clicfg_matrix_trace_fps_time_slice", 9);
    lJx = new b("clicfg_matrix_trace_load_activity_threshold", 10);
    lJy = new b("clicfg_matrix_trace_evil_method_threshold", 11);
    lJz = new b("clicfg_matrix_trace_fps_report_threshold", 12);
    lJA = new b("clicfg_matrix_trace_max_evil_method_stack_num", 13);
    lJB = new b("clicfg_matrix_trace_max_evil_method_try_trim_num", 14);
    lJC = new b("clicfg_matrix_trace_min_evil_method_druration", 15);
    lJD = new b("clicfg_matrix_trace_time_upload_duration", 16);
    lJE = new b("clicfg_matrix_fps_dropped_normal", 17);
    lJF = new b("clicfg_matrix_fps_dropped_middle", 18);
    lJG = new b("clicfg_matrix_fps_dropped_high", 19);
    lJH = new b("clicfg_matrix_fps_dropped_frozen", 20);
    lJI = new b("clicfg_matrix_trace_evil_method_enable", 21);
    lJJ = new b("clicfg_matrix_trace_app_start_up_threshold", 22);
    lJK = new b("clicfg_matrix_trace_fps_frame_fresh_threshold", 23);
    lJL = new b("clicfg_matrix_trace_min_evil_method_run_cnt", 24);
    lJM = new b("clicfg_matrix_trace_min_evil_method_dur_time", 25);
    lJN = new b("clicfg_matrix_trace_splash_activity_name", 26);
    lJO = new b("clicfg_matrix_io_file_io_main_thread_enable", 27);
    lJP = new b("clicfg_matrix_io_main_thread_enable_threshold", 28);
    lJQ = new b("clicfg_matrix_io_small_buffer_enable", 29);
    lJR = new b("clicfg_matrix_io_small_buffer_threshold", 30);
    lJS = new b("clicfg_matrix_io_small_buffer_operator_times", 31);
    lJT = new b("clicfg_matrix_io_repeated_read_enable", 32);
    lJU = new b("clicfg_matrix_io_repeated_read_threshold", 33);
    lJV = new b("clicfg_matrix_io_closeable_leak_enable", 34);
    lJW = new b("clicfg_matrix_battery_detect_wake_lock_enable", 35);
    lJX = new b("clicfg_matrix_battery_record_wake_lock_enable", 36);
    lJY = new b("clicfg_matrix_battery_wake_lock_hold_time_threshold", 37);
    lJZ = new b("clicfg_matrix_battery_wake_lock_1h_acquire_cnt_threshold", 38);
    lKa = new b("clicfg_matrix_battery_wake_lock_1h_hold_time_threshold", 39);
    lKb = new b("clicfg_matrix_battery_detect_alarm_enable", 40);
    lKc = new b("clicfg_matrix_battery_record_alarm_enable", 41);
    lKd = new b("clicfg_matrix_battery_alarm_1h_trigger_cnt_threshold", 42);
    lKe = new b("clicfg_matrix_battery_wake_up_alarm_1h_trigger_cnt_threshold", 43);
    lKf = new b("clicfg_matrix_memory_middle_min_span", 44);
    lKg = new b("clicfg_matrix_memory_high_min_span", 45);
    lKh = new b("clicfg_matrix_memory_threshold", 46);
    lKi = new b("clicfg_matrix_memory_special_activities", 47);
    lKj = new b("clicfg_matrix_resource_detect_interval_millis", 48);
    lKk = new b("clicfg_matrix_resource_max_detect_times", 49);
    lKl = new b("clicfg_matrix_resource_dump_hprof_enable", 50);
    lKm = new b("clicfg_matrix_thread_check_time", 51);
    lKn = new b("clicfg_matrix_thread_report_time", 52);
    lKo = new b("clicfg_matrix_thread_contain_sys", 53);
    lKp = new b("clicfg_matrix_thread_filter_thread_set", 54);
    lKq = new b("clicfg_android_process_native", 55);
    lKr = new b("clicfg_android_process_vm", 56);
    lKs = new b("clicfg_android_process_java", 57);
    lKt = new b("clicfg_android_process_work_begin", 58);
    lKu = new b("clicfg_android_process_work_end", 59);
    lKv = new b("clicfg_android_process_enable", 60);
    lKw = new b("clicfg_android_process_is_hard_mode", 61);
    lKx = new b("clicfg_android_process_is_check_launcher_ui", 62);
    lKy = new b("clicfg_android_process_check_time", 63);
    lKz = new b("clicfg_android_process_jiffy_per_min", 64);
    lKA = new b("clicfg_android_process_traffic_per_min", 65);
    lKB = new b("clicfg_android_process_hard_info", 66);
    lKC = new b("clicfg_turnoff_tools_weapp", 67);
    lKD = new b("clicfg_appbrand_process_preload_memory_stress_time_limit", 68);
    lKE = new b("clicfg_appbrand_process_preload_frequence_limit", 69);
    lKF = new b("clicfg_tencent_map_download_page_direct", 70);
    lKG = new b("clicfg_j2v8_snapshot", 71);
    lKH = new b("clicfg_j2v8_codecache", 72);
    lKI = new b("clicfg_story_open", 73);
    lKJ = new b("clicfg_story_upgrades", 74);
    lKK = new b("clicfg_story_pre_click", 75);
    lKL = new b("clicfg_story_preload_strategy", 76);
    lKM = new b("clicfg_story_preload_speed_good", 77);
    lKN = new b("clicfg_story_preload_speed_bad", 78);
    lKO = new b("clicfg_story_preload_force_preload", 79);
    lKP = new b("clicfg_story_preload_force_canload", 80);
    lKQ = new b("clicfg_story_preload_with_enter_sns", 81);
    lKR = new b("clicfg_story_preload_with_enter_pop_sns", 82);
    lKS = new b("clicfg_story_preload_with_change_sns", 83);
    lKT = new b("clicfg_story_sns_story_open", 84);
    lKU = new b("clicfg_story_music_story_thumb_size", 85);
    lKV = new b("clicfg_media_iframe", 86);
    lKW = new b("clicfg_hellhound_switch", 87);
    lKX = new b("clicfg_hellhound_frontback_switch", 88);
    lKY = new b("clicfg_hellhound_session_switch", 89);
    lKZ = new b("clicfg_hellhound_timeline_switch", 90);
    lLa = new b("clicfg_webview_preview_img_with_ani", 91);
    lLb = new b("clicfg_webview_show_ssl_dialog", 92);
    lLc = new b("clicfg_webview_skip_user_cert", 93);
    lLd = new b("clicfg_webview_can_pre_inject_jsbridge", 94);
    lLe = new b("clicfg_webview_can_call_jsapi_before_loaded", 95);
    lLf = new b("clicfg_android_xweb_code_cache", 96);
    lLg = new b("clicfg_weixin_mm_app_mgr", 97);
    lLh = new b("clicfg_weixin_mm_life_call", 98);
    lLi = new b("clicfg_weixin_mm_hell_hound", 99);
    lLj = new b("clicfg_weixin_rpt_mm_app_mgr", 100);
    lLk = new b("clicfg_weixin_rpt_mm_life_call", 101);
    lLl = new b("clicfg_weixin_rpt_mm_hell_hound", 102);
    lLm = new b("clicfg_weixin_register_mm_life_call", 103);
    lLn = new b("clicfg_weixin_register_mm_app_active_event", 104);
    lLo = new b("clicfg_waservice_webgl_component", 105);
    lLp = new b("clicfg_magicbrush_allow_antialias", 106);
    lLq = new b("clicfg_magicbrush_gcfactor", 107);
    lLr = new b("clicfg_magicbrush_autogcfactor_max_canvas", 108);
    lLs = new b("clicfg_magicbrush_autogcfactor_min_canvas", 109);
    lLt = new b("clicfg_magicbrush_autogcfactor_total_memory_ratio", 110);
    lLu = new b("clicfg_magicbrush_wxbct", 111);
    lLv = new b("clicfg_appbrand_socket_wcwss", 112);
    lLw = new b("clicfg_appbrand_game_socket_wcwss", 113);
    lLx = new b("clicfg_android_wxa_use_xweb_map", 114);
    lLy = new b("clicfg_use_new_cached_imei_method", 115);
    lLz = new b("clicfg_android_appbrand_page_reload_eanble", 116);
    lLA = new b("clicfg_emoji_high_total_mem", 117);
    lLB = new b("clicfg_emoji_high_mem_class", 118);
    lLC = new b("clicfg_emoji_high_preview_size", 119);
    lLD = new b("clicfg_emoji_high_sample_size", 120);
    lLE = new b("clicfg_emoji_low_preview_size", 121);
    lLF = new b("clicfg_emoji_low_sample_size", 122);
    lLG = new b("clicfg_emoji_sdk_enablelog", 123);
    lLH = new b("clicfg_emoji_segment_crash_auto_count", 124);
    lLI = new b("clicfg_emoji_segment_crash_manual_count", 125);
    lLJ = new b("clicfg_nodejs_websocket_open", 126);
    lLK = new b("clicfg_nodejs_fs_open", 127);
    lLL = new b("clicfg_target26_start_service_switch", 128);
    lLM = new b("clicfg_target26_start_service_manufacturer", 129);
    lLN = new b("clicfg_if_show_ignore_battery_optimizations", 130);
    lLO = new b("clicfg_target26_start_service_manu_exclusive", 131);
    lLP = new b("clicfg_target26_start_service_switch_huawei", 132);
    lLQ = new b("clicfg_target26_start_service_huawei_info", 133);
    lLR = new b("clicfg_remuxer_with_surface_timestamp", 134);
    lLS = new b("clicfg_target26_voice_focus_shield_sw", 135);
    lLT = new b("clicfg_appbrand_game_splashscreen", 136);
    lLU = new b[] { lJn, lJo, lJp, lJq, lJr, lJs, lJt, lJu, lJv, lJw, lJx, lJy, lJz, lJA, lJB, lJC, lJD, lJE, lJF, lJG, lJH, lJI, lJJ, lJK, lJL, lJM, lJN, lJO, lJP, lJQ, lJR, lJS, lJT, lJU, lJV, lJW, lJX, lJY, lJZ, lKa, lKb, lKc, lKd, lKe, lKf, lKg, lKh, lKi, lKj, lKk, lKl, lKm, lKn, lKo, lKp, lKq, lKr, lKs, lKt, lKu, lKv, lKw, lKx, lKy, lKz, lKA, lKB, lKC, lKD, lKE, lKF, lKG, lKH, lKI, lKJ, lKK, lKL, lKM, lKN, lKO, lKP, lKQ, lKR, lKS, lKT, lKU, lKV, lKW, lKX, lKY, lKZ, lLa, lLb, lLc, lLd, lLe, lLf, lLg, lLh, lLi, lLj, lLk, lLl, lLm, lLn, lLo, lLp, lLq, lLr, lLs, lLt, lLu, lLv, lLw, lLx, lLy, lLz, lLA, lLB, lLC, lLD, lLE, lLF, lLG, lLH, lLI, lLJ, lLK, lLL, lLM, lLN, lLO, lLP, lLQ, lLR, lLS, lLT };
    AppMethodBeat.o(128624);
  }
}

/* Location:           C:\Users\Lin\Downloads\dex-tools-2.1-SNAPSHOT\dex-tools-2.1-SNAPSHOT\classes-dex2jar.jar
 * Qualified Name:     com.tencent.mm.plugin.expt.a.a.b
 * JD-Core Version:    0.6.2
 */