package com.tencent.mm.g.b.a;

import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.mm.plugin.report.a;
import com.tencent.mm.sdk.platformtools.bo;
import java.util.Arrays;

public final class d extends a
{
  private int cTF;
  private long cTG;
  private long cTH;
  private long cTI;
  private long cTJ;
  private long cTK;
  private long cTL;
  private long cTM;
  private long cTN;
  private String cTO;
  private long cTP;
  private String cTQ;
  private long cTR;
  private long cTS;
  private long cTT;
  private long cTU;
  private long cTV;
  private long cTW;
  private long cTX;
  private long cTY;
  private long cTZ;
  private int cUA;
  private String cUB;
  private long cUC;
  private String cUD;
  private long cUE;
  private String cUF;
  private long cUG;
  private String cUH;
  private long cUI;
  private long cUJ;
  private long cUK;
  private long cUL;
  private long cUa;
  private long cUb;
  private long cUc;
  private long cUd;
  private String cUe;
  private long cUf;
  private long cUg;
  private long cUh;
  private long cUi;
  private long cUj;
  private long cUk;
  private long cUl;
  private long cUm;
  private long cUn;
  private long cUo;
  private long cUp;
  private long cUq;
  private long cUr;
  private long cUs;
  private long cUt;
  private long cUu;
  private long cUv;
  private long cUw;
  private long cUx;
  private long cUy;
  private long cUz;

  public d()
  {
    this.cTF = 0;
    this.cTG = 0L;
    this.cTH = 0L;
    this.cTI = 0L;
    this.cTJ = 0L;
    this.cTK = 0L;
    this.cTL = 0L;
    this.cTM = 0L;
    this.cTN = 0L;
    this.cTO = "";
    this.cTP = 0L;
    this.cTQ = "";
    this.cTR = 0L;
    this.cTS = 0L;
    this.cTT = 0L;
    this.cTU = 0L;
    this.cTV = 0L;
    this.cTW = 0L;
    this.cTX = 0L;
    this.cTY = 0L;
    this.cTZ = 0L;
    this.cUa = 0L;
    this.cUb = 0L;
    this.cUc = 0L;
    this.cUd = 0L;
    this.cUe = "";
    this.cUf = 0L;
    this.cUg = 0L;
    this.cUh = 0L;
    this.cUi = 0L;
    this.cUj = 0L;
    this.cUk = 0L;
    this.cUl = 0L;
    this.cUm = 0L;
    this.cUn = 0L;
    this.cUo = 0L;
    this.cUp = 0L;
    this.cUq = 0L;
    this.cUr = 0L;
    this.cUs = 0L;
    this.cUt = 0L;
    this.cUu = 0L;
    this.cUv = 0L;
    this.cUw = 0L;
    this.cUx = 0L;
    this.cUy = 0L;
    this.cUz = 0L;
    this.cUA = 0;
    this.cUB = "";
    this.cUC = 0L;
    this.cUD = "";
    this.cUE = 0L;
    this.cUF = "";
    this.cUG = 0L;
    this.cUH = "";
    this.cUI = 0L;
    this.cUJ = 0L;
    this.cUK = 0L;
    this.cUL = 0L;
  }

  public d(String paramString)
  {
    AppMethodBeat.i(77576);
    this.cTF = 0;
    this.cTG = 0L;
    this.cTH = 0L;
    this.cTI = 0L;
    this.cTJ = 0L;
    this.cTK = 0L;
    this.cTL = 0L;
    this.cTM = 0L;
    this.cTN = 0L;
    this.cTO = "";
    this.cTP = 0L;
    this.cTQ = "";
    this.cTR = 0L;
    this.cTS = 0L;
    this.cTT = 0L;
    this.cTU = 0L;
    this.cTV = 0L;
    this.cTW = 0L;
    this.cTX = 0L;
    this.cTY = 0L;
    this.cTZ = 0L;
    this.cUa = 0L;
    this.cUb = 0L;
    this.cUc = 0L;
    this.cUd = 0L;
    this.cUe = "";
    this.cUf = 0L;
    this.cUg = 0L;
    this.cUh = 0L;
    this.cUi = 0L;
    this.cUj = 0L;
    this.cUk = 0L;
    this.cUl = 0L;
    this.cUm = 0L;
    this.cUn = 0L;
    this.cUo = 0L;
    this.cUp = 0L;
    this.cUq = 0L;
    this.cUr = 0L;
    this.cUs = 0L;
    this.cUt = 0L;
    this.cUu = 0L;
    this.cUv = 0L;
    this.cUw = 0L;
    this.cUx = 0L;
    this.cUy = 0L;
    this.cUz = 0L;
    this.cUA = 0;
    this.cUB = "";
    this.cUC = 0L;
    this.cUD = "";
    this.cUE = 0L;
    this.cUF = "";
    this.cUG = 0L;
    this.cUH = "";
    this.cUI = 0L;
    this.cUJ = 0L;
    this.cUK = 0L;
    this.cUL = 0L;
    String[] arrayOfString;
    if (paramString != null)
    {
      arrayOfString = paramString.split(",");
      if (arrayOfString != null)
      {
        if (arrayOfString.length >= 59)
          break label1086;
        paramString = new String[59];
        Arrays.fill(paramString, 0, 59, "");
        System.arraycopy(arrayOfString, 0, paramString, 0, arrayOfString.length);
      }
    }
    while (true)
    {
      this.cTF = bo.getInt(paramString[0], 0);
      this.cTG = bo.getLong(paramString[1], 0L);
      this.cTH = bo.getLong(paramString[2], 0L);
      this.cTI = bo.getLong(paramString[3], 0L);
      this.cTJ = bo.getLong(paramString[4], 0L);
      this.cTK = bo.getLong(paramString[5], 0L);
      this.cTL = bo.getLong(paramString[6], 0L);
      this.cTM = bo.getLong(paramString[7], 0L);
      this.cTN = bo.getLong(paramString[8], 0L);
      this.cTO = t("SvrIP", paramString[9], true);
      this.cTP = bo.getLong(paramString[10], 0L);
      this.cTQ = t("FileKey", paramString[11], true);
      this.cTR = bo.getLong(paramString[12], 0L);
      this.cTS = bo.getLong(paramString[13], 0L);
      this.cTT = bo.getLong(paramString[14], 0L);
      this.cTU = bo.getLong(paramString[15], 0L);
      this.cTV = bo.getLong(paramString[16], 0L);
      this.cTW = bo.getLong(paramString[17], 0L);
      this.cTX = bo.getLong(paramString[18], 0L);
      this.cTY = bo.getLong(paramString[19], 0L);
      this.cTZ = bo.getLong(paramString[20], 0L);
      this.cUa = bo.getLong(paramString[21], 0L);
      this.cUb = bo.getLong(paramString[22], 0L);
      this.cUc = bo.getLong(paramString[23], 0L);
      this.cUd = bo.getLong(paramString[24], 0L);
      this.cUe = t("UUID", paramString[25], true);
      this.cUf = bo.getLong(paramString[26], 0L);
      this.cUg = bo.getLong(paramString[27], 0L);
      this.cUh = bo.getLong(paramString[28], 0L);
      this.cUi = bo.getLong(paramString[29], 0L);
      this.cUj = bo.getLong(paramString[30], 0L);
      this.cUk = bo.getLong(paramString[31], 0L);
      this.cUl = bo.getLong(paramString[32], 0L);
      this.cUm = bo.getLong(paramString[33], 0L);
      this.cUn = bo.getLong(paramString[34], 0L);
      this.cUo = bo.getLong(paramString[35], 0L);
      this.cUp = bo.getLong(paramString[36], 0L);
      this.cUq = bo.getLong(paramString[37], 0L);
      this.cUr = bo.getLong(paramString[38], 0L);
      this.cUs = bo.getLong(paramString[39], 0L);
      this.cUt = bo.getLong(paramString[40], 0L);
      this.cUu = bo.getLong(paramString[41], 0L);
      this.cUv = bo.getLong(paramString[42], 0L);
      this.cUw = bo.getLong(paramString[43], 0L);
      this.cUx = bo.getLong(paramString[44], 0L);
      this.cUy = bo.getLong(paramString[45], 0L);
      this.cUz = bo.getLong(paramString[46], 0L);
      this.cUA = bo.getInt(paramString[47], 0);
      this.cUB = t("UsedIp1", paramString[48], true);
      this.cUC = bo.getLong(paramString[49], 0L);
      this.cUD = t("UsedIp2", paramString[50], true);
      this.cUE = bo.getLong(paramString[51], 0L);
      this.cUF = t("UsedIp3", paramString[52], true);
      this.cUG = bo.getLong(paramString[53], 0L);
      this.cUH = t("UsedIp4", paramString[54], true);
      this.cUI = bo.getLong(paramString[55], 0L);
      this.cUJ = bo.getLong(paramString[56], 0L);
      this.cUK = bo.getLong(paramString[57], 0L);
      this.cUL = bo.getLong(paramString[58], 0L);
      AppMethodBeat.o(77576);
      return;
      label1086: paramString = arrayOfString;
    }
  }

  public final String Fj()
  {
    AppMethodBeat.i(77577);
    Object localObject = new StringBuffer();
    ((StringBuffer)localObject).append(this.cTF);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTG);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTH);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTI);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTJ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTK);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTL);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTM);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTN);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTO);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTP);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTQ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTR);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTS);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTT);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTU);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTV);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTW);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTX);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTY);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cTZ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUa);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUb);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUc);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUd);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUe);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUf);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUg);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUh);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUi);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUj);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUk);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUl);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUm);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUn);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUo);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUp);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUq);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUr);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUs);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUt);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUu);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUv);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUw);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUx);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUy);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUz);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUA);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUB);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUC);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUD);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUE);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUF);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUG);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUH);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUI);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUJ);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUK);
    ((StringBuffer)localObject).append(",");
    ((StringBuffer)localObject).append(this.cUL);
    localObject = ((StringBuffer)localObject).toString();
    VX((String)localObject);
    AppMethodBeat.o(77577);
    return localObject;
  }

  public final String Fk()
  {
    AppMethodBeat.i(77578);
    Object localObject = new StringBuffer();
    ((StringBuffer)localObject).append("CientErrNo:").append(this.cTF);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("OpType:").append(this.cTG);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("OpStartTs:").append(this.cTH);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("OpEndTs:").append(this.cTI);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("NetType:").append(this.cTJ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FileType:").append(this.cTK);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FileSize:").append(this.cTL);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CDNErrNo:").append(this.cTM);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CDNOpType:").append(this.cTN);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SvrIP:").append(this.cTO);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("IPCount:").append(this.cTP);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("FileKey:").append(this.cTQ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SliceCount:").append(this.cTR);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransportSize:").append(this.cTS);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnTotalCost:").append(this.cTT);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnTryTimes:").append(this.cTU);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CDNTransfStartTs:").append(this.cTV);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CDNTransfEndTs:").append(this.cTW);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("IsHitCache:").append(this.cTX);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("CompressPicLevel:").append(this.cTY);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SrcFileSize:").append(this.cTZ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ImgSource:").append(this.cUa);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ResolutionX:").append(this.cUb);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ResolutionY:").append(this.cUc);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ReportCode:").append(this.cUd);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UUID:").append(this.cUe);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ETLTime:").append(this.cUf);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PTLTime:").append(this.cUg);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ETLSize:").append(this.cUh);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("PTLSize:").append(this.cUi);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SkeyFailCount:").append(this.cUj);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("SKeyTimeoutCount:").append(this.cUk);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectCount:").append(this.cUl);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectTotalMS:").append(this.cUm);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectAvgMS:").append(this.cUn);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectVarianceMS:").append(this.cUo);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectMinMS:").append(this.cUp);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnectMaxMS:").append(this.cUq);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforCount:").append(this.cUr);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforTotalMS:").append(this.cUs);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforAvgMS:").append(this.cUt);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforVarianceMS:").append(this.cUu);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforMinMS:").append(this.cUv);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("TransforMaxMS:").append(this.cUw);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("IsProgressiveJPEG:").append(this.cUx);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("WaitSec:").append(this.cUy);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("LastPort:").append(this.cUz);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("ConnErrorCode:").append(this.cUA);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedIp1:").append(this.cUB);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedPort1:").append(this.cUC);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedIp2:").append(this.cUD);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedPort2:").append(this.cUE);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedIp3:").append(this.cUF);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedPort3:").append(this.cUG);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedIp4:").append(this.cUH);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("UsedPort4:").append(this.cUI);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("LogCreateTime:").append(this.cUJ);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("LogReportTime:").append(this.cUK);
    ((StringBuffer)localObject).append("\r\n");
    ((StringBuffer)localObject).append("LogReportSvrTime:").append(this.cUL);
    localObject = ((StringBuffer)localObject).toString();
    AppMethodBeat.o(77578);
    return localObject;
  }

  public final int getId()
  {
    return 13937;
  }
}

/* Location:           C:\Users\Lin\Downloads\dex-tools-2.1-SNAPSHOT\dex-tools-2.1-SNAPSHOT\classes7-dex2jar.jar
 * Qualified Name:     com.tencent.mm.g.b.a.d
 * JD-Core Version:    0.6.2
 */